COCO_FR = {
    "person": "personne",
    "bicycle": "vélo",
    "car": "voiture",
    "motorcycle": "moto",
    "airplane": "avion",
    "bus": "bus",
    "train": "train",
    "truck": "camion",
    "boat": "bateau",
    "traffic light": "feu de circulation",
    "fire hydrant": "bouche d'incendie",
    "stop sign": "panneau stop",
    "parking meter": "parcmètre",
    "bench": "banc",
    "bird": "oiseau",
    "cat": "chat",
    "dog": "chien",
    "horse": "cheval",
    "sheep": "mouton",
    "cow": "vache",
    "elephant": "éléphant",
    "bear": "ours",
    "zebra": "zèbre",
    "giraffe": "girafe",
    "backpack": "sac à dos",
    "umbrella": "parapluie",
    "handbag": "sac à main",
    "tie": "cravate",
    "suitcase": "valise",
    "frisbee": "frisbee",
    "skis": "skis",
    "snowboard": "snowboard",
    "sports ball": "ballon de sport",
    "kite": "cerf-volant",
    "baseball bat": "batte de baseball",
    "baseball glove": "gant de baseball",
    "skateboard": "skateboard",
    "surfboard": "planche de surf",
    "tennis racket": "raquette de tennis",
    "bottle": "bouteille",
    "wine glass": "verre à vin",
    "cup": "tasse",
    "fork": "fourchette",
    "knife": "couteau",
    "spoon": "cuillère",
    "bowl": "bol",
    "banana": "banane",
    "apple": "pomme",
    "sandwich": "sandwich",
    "orange": "orange",
    "broccoli": "brocoli",
    "carrot": "carotte",
    "hot dog": "hot-dog",
    "pizza": "pizza",
    "donut": "beignet",
    "cake": "gâteau",
    "chair": "chaise",
    "couch": "canapé",
    "potted plant": "plante en pot",
    "bed": "lit",
    "dining table": "table à manger",
    "toilet": "toilettes",
    "tv": "télévision",
    "laptop": "ordinateur portable",
    "mouse": "souris",
    "remote": "télécommande",
    "keyboard": "clavier",
    "cell phone": "téléphone portable",
    "microwave": "micro-ondes",
    "oven": "four",
    "toaster": "grille-pain",
    "sink": "évier",
    "refrigerator": "réfrigérateur",
    "book": "livre",
    "clock": "horloge",
    "vase": "vase",
    "scissors": "ciseaux",
    "teddy bear": "ours en peluche",
    "hair drier": "sèche-cheveux",
    "toothbrush": "brosse à dents",
    # Classes du modèle threat-yolov8n (détection de menaces)
    "Gun": "arme à feu",
    "explosion": "explosion",
    "grenade": "grenade",
    "knife": "couteau",
    # Classes du modèle fire-yolo11s (feu / fumée)
    "Fire": "feu",
    "Smoke": "fumée",
    # Classe du modèle plate-yolov11n (plaques d'immatriculation)
    "License_Plate": "plaque d'immatriculation",
    # Classes du modèle fight-yolov8s (bagarre / violence)
    "violence": "bagarre",
    "non_violence": "calme",
    # Classes du modèle ppe-yolov8s (équipements de sécurité)
    "Person": "personne",
    "Hardhat": "casque",
    "NO-Hardhat": "pas de casque",
    "Mask": "masque",
    "NO-Mask": "pas de masque",
    "Safety Vest": "gilet de sécurité",
    "NO-Safety Vest": "pas de gilet de sécurité",
    "Safety Cone": "cône de signalisation",
    "machinery": "machine",
    "vehicle": "véhicule",
    # Classes du modèle clothing-yolov8s-seg (type de vêtement)
    "short_sleeved_shirt": "chemise à manches courtes",
    "long_sleeved_shirt": "chemise à manches longues",
    "short_sleeved_outwear": "veste à manches courtes",
    "long_sleeved_outwear": "veste à manches longues",
    "vest": "gilet",
    "sling": "débardeur fin",
    "shorts": "short",
    "trousers": "pantalon",
    "skirt": "jupe",
    "short_sleeved_dress": "robe à manches courtes",
    "long_sleeved_dress": "robe à manches longues",
    "vest_dress": "robe sans manches",
    "sling_dress": "robe à bretelles fines",
}
